# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a76e39242c8818e2460ecfcf7e1402de08371c831252d9e956772ab7c98981e3237633d8680cb705c53030ae19ea6ec51e2d264fb9bfd55d0af7b5f9b061967

test:
  secret_key_base: 5a683a5a1d954f626b33a2488668e51d559b59940ef57af2f6428b11d2e1ebf66e080a5f16aba08b0864ac693dbdfce673d9998548eb08ed01037fa301dc0489

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
